# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: 
          chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Tests
      run: ./gradlew test --info # Run our tests using Gradle

    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
      # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
      # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      # comma-separated string, send email to
        to: vig92007@gmail.com
      # from email name
        from: Surya Chatradi
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
          name: Run Tests            # Name of the check run which will be created
          path: build/test-results/test/TEST-*.xml    # Path to test results
          reporter: java-junit
  
  
